apiVersion: apps/v1
kind: Deployment
metadata:
  name: examserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examserver
  template:
    metadata:
      labels:
        app: examserver
    spec:
      containers:
        - name: examserver
          image: examserver:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/ttqt_acb_sit_phase6
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres