server.port=8090

spring.application.name=socket-server

# websocket
spring.websocket.path=/ws

# logging
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG